version: '0.1' # Verion

services:
  db:
    image: postgres:14.18
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: StackStep
    volumes:
      - ./postgres:/var/lib/postgresql/data